In [1]:
import numpy
import random
n=100
a = numpy.zeros(shape=(n,n))
for r in range(n):
    for c in range(n):
        #print(i,j)
        if(r==c):
            a[r][c]=1 #Diagonal values
        elif(r<c):
            ran=random.randrange(0,9,1)
            a[r][c]=ran
            a[c][r]=ran
print(a)

[[1. 6. 1. ... 8. 4. 8.]
 [6. 1. 0. ... 1. 2. 8.]
 [1. 0. 1. ... 7. 6. 5.]
 ...
 [8. 1. 7. ... 1. 4. 7.]
 [4. 2. 6. ... 4. 1. 3.]
 [8. 8. 5. ... 7. 3. 1.]]


In [1]:
import pandas as pd
import numpy
import random
################################
n=250
################################
print('Generating graph.csv file : ',end ='')
data_frame = pd.DataFrame(columns=['Source', 'Destination', 'Weight'])

ones = 1

print('Creating')

for r in range(n):
    if(((r+1)/n*100)%1==0):
        print("{0:.2f} %".format((r+1)/n*100))
    for c in range(n):
        
        #print(i,j)
        if(r==c):
            df_t = pd.DataFrame([[r,c,ones]],columns=['Source', 'Destination', 'Weight'])
            data_frame = pd.concat([data_frame, df_t], ignore_index=True)
        elif(r>c):
            #print(r,c,end= " ")
            ran=random.randrange(0,1000,50)
            df_t = pd.DataFrame([[r,c,ran]],columns=['Source', 'Destination', 'Weight'])
            data_frame = pd.concat([data_frame, df_t], ignore_index=True)
    
data_frame.to_csv('graph2.csv', mode='a',index=False,header=False)
print('Completed')


Generating graph.csv file : Creating
2.00 %
4.00 %
6.00 %
8.00 %
10.00 %
12.00 %
16.00 %
18.00 %
20.00 %
22.00 %
24.00 %
26.00 %
30.00 %
32.00 %
34.00 %
36.00 %
38.00 %
40.00 %
42.00 %
44.00 %
46.00 %
48.00 %
50.00 %
52.00 %
54.00 %
60.00 %
62.00 %
64.00 %
66.00 %
68.00 %
70.00 %
72.00 %
74.00 %
76.00 %
78.00 %
80.00 %
82.00 %
84.00 %
86.00 %
88.00 %
90.00 %
92.00 %
94.00 %
96.00 %
98.00 %
100.00 %
Completed


In [ ]:
print("{0:.2f} %".format((r+1)/n*100))